apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: store-gateway
  namespace: pets
spec:
  gatewayClassName: approuting-istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: store-front
  namespace: pets
spec:
  parentRefs:
    - name: store-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: store-front
          port: 80
